services:
  frontend:
    image: frontend:latest
    hostname: frontend
    privileged: true
    networks:
      webnet_test:
    ports:
      - 8080:80

  backend:
    image: backend:latest
    hostname: backend
    privileged: true
    networks:
     webnet_test:


networks:
  webnet_test:
   driver: bridge
